// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
//
// THIS FILE IS AUTOGENERATED BY CARGO-LIBBPF-GEN!

pub use self::imp::*;

#[allow(dead_code)]
#[allow(non_snake_case)]
#[allow(non_camel_case_types)]
#[allow(clippy::absolute_paths)]
#[allow(clippy::upper_case_acronyms)]
#[allow(clippy::zero_repeat_side_effects)]
#[warn(single_use_lifetimes)]
mod imp {
    #[allow(unused_imports)]
    use super::*;
    use libbpf_rs::libbpf_sys;
    use libbpf_rs::skel::OpenSkel;
    use libbpf_rs::skel::Skel;
    use libbpf_rs::skel::SkelBuilder;
    use libbpf_rs::AsRawLibbpf as _;
    use libbpf_rs::MapCore as _;
    fn build_skel_config(
    ) -> libbpf_rs::Result<libbpf_rs::__internal_skel::ObjectSkeletonConfig<'static>> {
        let mut builder = libbpf_rs::__internal_skel::ObjectSkeletonConfigBuilder::new(DATA);
        builder
            .name("program_bpf")
            .map("traffic", false)
            .prog("bpf_program");
        builder.build()
    }
    pub struct OpenProgramMaps<'obj> {
        pub traffic: libbpf_rs::OpenMapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenProgramMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::OpenObject,
        ) -> libbpf_rs::Result<Self> {
            let mut traffic = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "traffic" => traffic = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                traffic: traffic.expect("map `traffic` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct ProgramMaps<'obj> {
        pub traffic: libbpf_rs::MapMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> ProgramMaps<'obj> {
        #[allow(unused_variables)]
        unsafe fn new(
            config: &libbpf_rs::__internal_skel::ObjectSkeletonConfig<'_>,
            object: &mut libbpf_rs::Object,
        ) -> libbpf_rs::Result<Self> {
            let mut traffic = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::Object, &'obj mut libbpf_rs::Object>(object)
            };
            #[allow(clippy::never_loop)]
            for map in object.maps_mut() {
                let name = map.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "map has invalid name",
                    ))
                })?;
                #[allow(clippy::match_single_binding)]
                match name {
                    "traffic" => traffic = Some(map),
                    _ => panic!("encountered unexpected map: `{name}`"),
                }
            }

            let slf = Self {
                traffic: traffic.expect("map `traffic` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct OpenProgramProgs<'obj> {
        pub bpf_program: libbpf_rs::OpenProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> OpenProgramProgs<'obj> {
        unsafe fn new(object: &mut libbpf_rs::OpenObject) -> libbpf_rs::Result<Self> {
            let mut bpf_program = None;
            let object = unsafe {
                std::mem::transmute::<&mut libbpf_rs::OpenObject, &'obj mut libbpf_rs::OpenObject>(
                    object,
                )
            };
            for prog in object.progs_mut() {
                let name = prog.name().to_str().ok_or_else(|| {
                    libbpf_rs::Error::from(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "prog has invalid name",
                    ))
                })?;
                match name {
                    "bpf_program" => bpf_program = Some(prog),
                    _ => panic!("encountered unexpected prog: `{name}`"),
                }
            }

            let slf = Self {
                bpf_program: bpf_program.expect("prog `bpf_program` not present"),
                _phantom: std::marker::PhantomData,
            };
            Ok(slf)
        }
    }
    pub struct ProgramProgs<'obj> {
        pub bpf_program: libbpf_rs::ProgramMut<'obj>,
        _phantom: std::marker::PhantomData<&'obj ()>,
    }

    impl<'obj> ProgramProgs<'obj> {
        #[allow(unused_variables)]
        fn new(open_progs: OpenProgramProgs<'obj>) -> Self {
            Self {
                bpf_program: unsafe {
                    libbpf_rs::ProgramMut::new_mut(
                        open_progs.bpf_program.as_libbpf_object().as_mut(),
                    )
                },
                _phantom: std::marker::PhantomData,
            }
        }
    }
    struct OwnedRef<'obj, O> {
        object: Option<&'obj mut std::mem::MaybeUninit<O>>,
    }

    impl<'obj, O> OwnedRef<'obj, O> {
        /// # Safety
        /// The object has to be initialized.
        unsafe fn new(object: &'obj mut std::mem::MaybeUninit<O>) -> Self {
            Self {
                object: Some(object),
            }
        }

        fn as_ref(&self) -> &O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_ref().unwrap().assume_init_ref() }
        }

        fn as_mut(&mut self) -> &mut O {
            // SAFETY: As per the contract during construction, the
            //         object has to be initialized.
            unsafe { self.object.as_mut().unwrap().assume_init_mut() }
        }

        fn take(mut self) -> &'obj mut std::mem::MaybeUninit<O> {
            self.object.take().unwrap()
        }
    }

    impl<O> Drop for OwnedRef<'_, O> {
        fn drop(&mut self) {
            if let Some(object) = &mut self.object {
                unsafe { object.assume_init_drop() }
            }
        }
    }

    #[derive(Default)]
    pub struct ProgramSkelBuilder {
        pub obj_builder: libbpf_rs::ObjectBuilder,
    }

    impl<'obj> ProgramSkelBuilder {
        fn open_opts_impl(
            self,
            open_opts: *const libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProgramSkel<'obj>> {
            let skel_config = build_skel_config()?;
            let skel_ptr = skel_config.as_libbpf_object();

            let ret =
                unsafe { libbpf_sys::bpf_object__open_skeleton(skel_ptr.as_ptr(), open_opts) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            // SAFETY: `skel_ptr` points to a valid object after the
            //         open call.
            let obj_ptr = unsafe { *skel_ptr.as_ref().obj };
            // SANITY: `bpf_object__open_skeleton` should have
            //         allocated the object.
            let obj_ptr = std::ptr::NonNull::new(obj_ptr).unwrap();
            // SAFETY: `obj_ptr` points to an opened object after
            //         skeleton open.
            let obj = unsafe { libbpf_rs::OpenObject::from_ptr(obj_ptr) };
            let _obj = object.write(obj);
            // SAFETY: We just wrote initialized data to `object`.
            let mut obj_ref = unsafe { OwnedRef::new(object) };

            #[allow(unused_mut)]
            let mut skel = OpenProgramSkel {
                maps: unsafe { OpenProgramMaps::new(&skel_config, obj_ref.as_mut())? },
                progs: unsafe { OpenProgramProgs::new(obj_ref.as_mut())? },
                obj: obj_ref,
                // SAFETY: Our `struct_ops` type contains only pointers,
                //         which are allowed to be NULL.
                // TODO: Generate and use a `Default` representation
                //       instead, to cut down on unsafe code.
                struct_ops: unsafe { std::mem::zeroed() },
                skel_config,
            };

            Ok(skel)
        }
    }

    impl<'obj> SkelBuilder<'obj> for ProgramSkelBuilder {
        type Output = OpenProgramSkel<'obj>;
        fn open(
            self,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProgramSkel<'obj>> {
            self.open_opts_impl(std::ptr::null(), object)
        }

        fn open_opts(
            self,
            open_opts: libbpf_sys::bpf_object_open_opts,
            object: &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
        ) -> libbpf_rs::Result<OpenProgramSkel<'obj>> {
            self.open_opts_impl(&open_opts, object)
        }

        fn object_builder(&self) -> &libbpf_rs::ObjectBuilder {
            &self.obj_builder
        }
        fn object_builder_mut(&mut self) -> &mut libbpf_rs::ObjectBuilder {
            &mut self.obj_builder
        }
    }

    #[derive(Debug, Clone)]
    #[repr(C)]
    pub struct StructOps {}

    impl StructOps {}
    pub mod types {
        #[allow(unused_imports)]
        use super::*;
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct __anon_1 {
            pub r#type: *mut [i32; 6],
            pub max_entries: *mut [i32; 2],
            pub key: *mut u32,
            pub value: *mut u64,
        }
        impl Default for __anon_1 {
            fn default() -> Self {
                Self {
                    r#type: std::ptr::null_mut(),
                    max_entries: std::ptr::null_mut(),
                    key: std::ptr::null_mut(),
                    value: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Default, Copy, Clone)]
        #[repr(C)]
        pub struct __sk_buff {
            pub len: u32,
            pub pkt_type: u32,
            pub mark: u32,
            pub queue_mapping: u32,
            pub protocol: u32,
            pub vlan_present: u32,
            pub vlan_tci: u32,
            pub vlan_proto: u32,
            pub priority: u32,
            pub ingress_ifindex: u32,
            pub ifindex: u32,
            pub tc_index: u32,
            pub cb: [u32; 5],
            pub hash: u32,
            pub tc_classid: u32,
            pub data: u32,
            pub data_end: u32,
            pub napi_id: u32,
            pub family: u32,
            pub remote_ip4: u32,
            pub local_ip4: u32,
            pub remote_ip6: [u32; 4],
            pub local_ip6: [u32; 4],
            pub remote_port: u32,
            pub local_port: u32,
            pub data_meta: u32,
            pub __anon_2: __anon_2,
            pub tstamp: u64,
            pub wire_len: u32,
            pub gso_segs: u32,
            pub __anon_3: __anon_3,
            pub gso_size: u32,
            pub tstamp_type: u8,
            pub hwtstamp: u64,
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_2 {
            pub flow_keys: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon_2 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_2 {
            fn default() -> Self {
                Self {
                    flow_keys: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Copy, Clone)]
        #[repr(C)]
        pub union __anon_3 {
            pub sk: *mut std::ffi::c_void,
        }
        impl std::fmt::Debug for __anon_3 {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "(???)")
            }
        }
        impl Default for __anon_3 {
            fn default() -> Self {
                Self {
                    sk: std::ptr::null_mut(),
                }
            }
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct maps {
            pub traffic: __anon_1,
        }
        #[derive(Debug, Copy, Clone)]
        #[repr(C)]
        pub struct license {
            pub _license: [i8; 4],
        }
    }
    pub struct OpenProgramSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::OpenObject>,
        pub maps: OpenProgramMaps<'obj>,
        pub progs: OpenProgramProgs<'obj>,
        pub struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
    }

    impl<'obj> OpenSkel<'obj> for OpenProgramSkel<'obj> {
        type Output = ProgramSkel<'obj>;
        fn load(self) -> libbpf_rs::Result<ProgramSkel<'obj>> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();

            let ret = unsafe { libbpf_sys::bpf_object__load_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            let obj_ref = self.obj.take();
            let open_obj = std::mem::replace(obj_ref, std::mem::MaybeUninit::uninit());
            // SAFETY: `open_obj` is guaranteed to be properly
            //         initialized as it came from an `OwnedRef`.
            let obj_ptr = unsafe { open_obj.assume_init().take_ptr() };
            // SAFETY: `obj_ptr` points to a loaded object after
            //         skeleton load.
            let obj = unsafe { libbpf_rs::Object::from_ptr(obj_ptr) };
            // SAFETY: `OpenObject` and `Object` are guaranteed to
            //         have the same memory layout.
            let obj_ref = unsafe {
                std::mem::transmute::<
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::OpenObject>,
                    &'obj mut std::mem::MaybeUninit<libbpf_rs::Object>,
                >(obj_ref)
            };
            let _obj = obj_ref.write(obj);
            // SAFETY: We just wrote initialized data to `obj_ref`.
            let mut obj_ref = unsafe { OwnedRef::new(obj_ref) };

            Ok(ProgramSkel {
                maps: unsafe { ProgramMaps::new(&self.skel_config, obj_ref.as_mut())? },
                progs: ProgramProgs::new(self.progs),
                obj: obj_ref,
                struct_ops: self.struct_ops,
                skel_config: self.skel_config,
                links: ProgramLinks::default(),
            })
        }

        fn open_object(&self) -> &libbpf_rs::OpenObject {
            self.obj.as_ref()
        }

        fn open_object_mut(&mut self) -> &mut libbpf_rs::OpenObject {
            self.obj.as_mut()
        }
    }
    #[derive(Default)]
    pub struct ProgramLinks {
        pub bpf_program: Option<libbpf_rs::Link>,
    }
    pub struct ProgramSkel<'obj> {
        obj: OwnedRef<'obj, libbpf_rs::Object>,
        pub maps: ProgramMaps<'obj>,
        pub progs: ProgramProgs<'obj>,
        struct_ops: StructOps,
        skel_config: libbpf_rs::__internal_skel::ObjectSkeletonConfig<'obj>,
        pub links: ProgramLinks,
    }

    unsafe impl Send for ProgramSkel<'_> {}
    unsafe impl Sync for ProgramSkel<'_> {}

    impl<'obj> Skel<'obj> for ProgramSkel<'obj> {
        fn object(&self) -> &libbpf_rs::Object {
            self.obj.as_ref()
        }

        fn object_mut(&mut self) -> &mut libbpf_rs::Object {
            self.obj.as_mut()
        }
        fn attach(&mut self) -> libbpf_rs::Result<()> {
            let skel_ptr = self.skel_config.as_libbpf_object().as_ptr();
            let ret = unsafe { libbpf_sys::bpf_object__attach_skeleton(skel_ptr) };
            if ret != 0 {
                return Err(libbpf_rs::Error::from_raw_os_error(-ret));
            }

            self.links = ProgramLinks {
                bpf_program: core::ptr::NonNull::new(self.skel_config.prog_link_ptr(0)?)
                    .map(|ptr| unsafe { libbpf_rs::Link::from_ptr(ptr) }),
            };

            Ok(())
        }
    }
    impl ProgramSkel<'_> {
        pub fn struct_ops_raw(&self) -> *const StructOps {
            &self.struct_ops
        }

        pub fn struct_ops(&self) -> &StructOps {
            &self.struct_ops
        }
    }
    const DATA: &[u8] = &[
        127, 69, 76, 70, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 247, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 104, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0,
        0, 64, 0, 9, 0, 1, 0, 0, 46, 115, 116, 114, 116, 97, 98, 0, 46, 115, 121, 109, 116, 97, 98,
        0, 115, 111, 99, 107, 101, 116, 0, 46, 109, 97, 112, 115, 0, 108, 105, 99, 101, 110, 115,
        101, 0, 112, 114, 111, 103, 114, 97, 109, 46, 98, 112, 102, 46, 99, 0, 76, 66, 66, 48, 95,
        50, 0, 76, 66, 66, 48, 95, 52, 0, 98, 112, 102, 95, 112, 114, 111, 103, 114, 97, 109, 0,
        116, 114, 97, 102, 102, 105, 99, 0, 95, 108, 105, 99, 101, 110, 115, 101, 0, 46, 114, 101,
        108, 115, 111, 99, 107, 101, 116, 0, 46, 66, 84, 70, 0, 46, 66, 84, 70, 46, 101, 120, 116,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 0, 0, 0, 4,
        0, 241, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 0, 0, 0, 0, 0, 3, 0, 40, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 59, 0, 0, 0, 0, 0, 3, 0, 112, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 66, 0, 0, 0, 18, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 78, 0,
        0, 0, 17, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 86, 0, 0, 0, 17, 0, 5,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 191, 22, 0, 0, 0, 0, 0, 0, 97, 98, 4, 0,
        0, 0, 0, 0, 183, 1, 0, 0, 1, 0, 0, 0, 85, 2, 1, 0, 4, 0, 0, 0, 183, 1, 0, 0, 0, 0, 0, 0,
        99, 26, 252, 255, 0, 0, 0, 0, 191, 162, 0, 0, 0, 0, 0, 0, 7, 2, 0, 0, 252, 255, 255, 255,
        24, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 133, 0, 0, 0, 1, 0, 0, 0, 21, 0, 2, 0, 0,
        0, 0, 0, 97, 97, 0, 0, 0, 0, 0, 0, 219, 16, 0, 0, 0, 0, 0, 0, 183, 0, 0, 0, 0, 0, 0, 0,
        149, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 71, 80, 76, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 6, 0, 0, 0, 159, 235, 1, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 27, 3, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 32, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 6, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0,
        1, 4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0,
        0, 0, 0, 2, 0, 0, 0, 4, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 8, 0, 0, 0, 25, 0, 0,
        0, 0, 0, 0, 8, 9, 0, 0, 0, 29, 0, 0, 0, 0, 0, 0, 8, 10, 0, 0, 0, 35, 0, 0, 0, 0, 0, 0, 1,
        4, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 12, 0, 0, 0, 48, 0, 0, 0, 0, 0, 0, 8, 13,
        0, 0, 0, 52, 0, 0, 0, 0, 0, 0, 8, 14, 0, 0, 0, 58, 0, 0, 0, 0, 0, 0, 1, 8, 0, 0, 0, 64, 0,
        0, 0, 0, 0, 0, 0, 4, 0, 0, 4, 32, 0, 0, 0, 77, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 82, 0, 0,
        0, 5, 0, 0, 0, 64, 0, 0, 0, 94, 0, 0, 0, 7, 0, 0, 0, 128, 0, 0, 0, 98, 0, 0, 0, 11, 0, 0,
        0, 192, 0, 0, 0, 104, 0, 0, 0, 0, 0, 0, 14, 15, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        2, 18, 0, 0, 0, 112, 0, 0, 0, 34, 0, 0, 4, 192, 0, 0, 0, 122, 0, 0, 0, 9, 0, 0, 0, 0, 0, 0,
        0, 126, 0, 0, 0, 9, 0, 0, 0, 32, 0, 0, 0, 135, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 140, 0, 0,
        0, 9, 0, 0, 0, 96, 0, 0, 0, 154, 0, 0, 0, 9, 0, 0, 0, 128, 0, 0, 0, 163, 0, 0, 0, 9, 0, 0,
        0, 160, 0, 0, 0, 176, 0, 0, 0, 9, 0, 0, 0, 192, 0, 0, 0, 185, 0, 0, 0, 9, 0, 0, 0, 224, 0,
        0, 0, 196, 0, 0, 0, 9, 0, 0, 0, 0, 1, 0, 0, 205, 0, 0, 0, 9, 0, 0, 0, 32, 1, 0, 0, 221, 0,
        0, 0, 9, 0, 0, 0, 64, 1, 0, 0, 229, 0, 0, 0, 9, 0, 0, 0, 96, 1, 0, 0, 238, 0, 0, 0, 19, 0,
        0, 0, 128, 1, 0, 0, 241, 0, 0, 0, 9, 0, 0, 0, 32, 2, 0, 0, 246, 0, 0, 0, 9, 0, 0, 0, 64, 2,
        0, 0, 1, 1, 0, 0, 9, 0, 0, 0, 96, 2, 0, 0, 6, 1, 0, 0, 9, 0, 0, 0, 128, 2, 0, 0, 15, 1, 0,
        0, 9, 0, 0, 0, 160, 2, 0, 0, 23, 1, 0, 0, 9, 0, 0, 0, 192, 2, 0, 0, 30, 1, 0, 0, 9, 0, 0,
        0, 224, 2, 0, 0, 41, 1, 0, 0, 9, 0, 0, 0, 0, 3, 0, 0, 51, 1, 0, 0, 20, 0, 0, 0, 32, 3, 0,
        0, 62, 1, 0, 0, 20, 0, 0, 0, 160, 3, 0, 0, 72, 1, 0, 0, 9, 0, 0, 0, 32, 4, 0, 0, 84, 1, 0,
        0, 9, 0, 0, 0, 64, 4, 0, 0, 95, 1, 0, 0, 9, 0, 0, 0, 96, 4, 0, 0, 0, 0, 0, 0, 21, 0, 0, 0,
        128, 4, 0, 0, 105, 1, 0, 0, 13, 0, 0, 0, 192, 4, 0, 0, 112, 1, 0, 0, 9, 0, 0, 0, 0, 5, 0,
        0, 121, 1, 0, 0, 9, 0, 0, 0, 32, 5, 0, 0, 0, 0, 0, 0, 23, 0, 0, 0, 64, 5, 0, 0, 130, 1, 0,
        0, 9, 0, 0, 0, 128, 5, 0, 0, 139, 1, 0, 0, 25, 0, 0, 0, 160, 5, 0, 0, 151, 1, 0, 0, 13, 0,
        0, 0, 192, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 9, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 9, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 5, 8, 0, 0, 0, 160, 1, 0, 0, 22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 32, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 5, 8, 0, 0, 0, 170, 1, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 2, 33, 0, 0, 0, 173, 1, 0, 0, 0, 0, 0, 8, 26, 0, 0, 0, 178, 1, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 13, 2, 0, 0, 0, 192, 1, 0, 0, 17, 0, 0, 0,
        196, 1, 0, 0, 1, 0, 0, 12, 27, 0, 0, 0, 208, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 29, 0, 0, 0, 4, 0, 0, 0, 4, 0, 0, 0, 213, 1, 0, 0, 0,
        0, 0, 14, 30, 0, 0, 0, 1, 0, 0, 0, 222, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 236, 1, 0, 0, 0,
        0, 0, 7, 0, 0, 0, 0, 6, 3, 0, 0, 1, 0, 0, 15, 32, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 32, 0,
        0, 0, 12, 3, 0, 0, 1, 0, 0, 15, 4, 0, 0, 0, 31, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 105,
        110, 116, 0, 95, 95, 65, 82, 82, 65, 89, 95, 83, 73, 90, 69, 95, 84, 89, 80, 69, 95, 95, 0,
        117, 51, 50, 0, 95, 95, 117, 51, 50, 0, 117, 110, 115, 105, 103, 110, 101, 100, 32, 105,
        110, 116, 0, 117, 54, 52, 0, 95, 95, 117, 54, 52, 0, 117, 110, 115, 105, 103, 110, 101,
        100, 32, 108, 111, 110, 103, 32, 108, 111, 110, 103, 0, 116, 121, 112, 101, 0, 109, 97,
        120, 95, 101, 110, 116, 114, 105, 101, 115, 0, 107, 101, 121, 0, 118, 97, 108, 117, 101, 0,
        116, 114, 97, 102, 102, 105, 99, 0, 95, 95, 115, 107, 95, 98, 117, 102, 102, 0, 108, 101,
        110, 0, 112, 107, 116, 95, 116, 121, 112, 101, 0, 109, 97, 114, 107, 0, 113, 117, 101, 117,
        101, 95, 109, 97, 112, 112, 105, 110, 103, 0, 112, 114, 111, 116, 111, 99, 111, 108, 0,
        118, 108, 97, 110, 95, 112, 114, 101, 115, 101, 110, 116, 0, 118, 108, 97, 110, 95, 116,
        99, 105, 0, 118, 108, 97, 110, 95, 112, 114, 111, 116, 111, 0, 112, 114, 105, 111, 114,
        105, 116, 121, 0, 105, 110, 103, 114, 101, 115, 115, 95, 105, 102, 105, 110, 100, 101, 120,
        0, 105, 102, 105, 110, 100, 101, 120, 0, 116, 99, 95, 105, 110, 100, 101, 120, 0, 99, 98,
        0, 104, 97, 115, 104, 0, 116, 99, 95, 99, 108, 97, 115, 115, 105, 100, 0, 100, 97, 116, 97,
        0, 100, 97, 116, 97, 95, 101, 110, 100, 0, 110, 97, 112, 105, 95, 105, 100, 0, 102, 97,
        109, 105, 108, 121, 0, 114, 101, 109, 111, 116, 101, 95, 105, 112, 52, 0, 108, 111, 99, 97,
        108, 95, 105, 112, 52, 0, 114, 101, 109, 111, 116, 101, 95, 105, 112, 54, 0, 108, 111, 99,
        97, 108, 95, 105, 112, 54, 0, 114, 101, 109, 111, 116, 101, 95, 112, 111, 114, 116, 0, 108,
        111, 99, 97, 108, 95, 112, 111, 114, 116, 0, 100, 97, 116, 97, 95, 109, 101, 116, 97, 0,
        116, 115, 116, 97, 109, 112, 0, 119, 105, 114, 101, 95, 108, 101, 110, 0, 103, 115, 111,
        95, 115, 101, 103, 115, 0, 103, 115, 111, 95, 115, 105, 122, 101, 0, 116, 115, 116, 97,
        109, 112, 95, 116, 121, 112, 101, 0, 104, 119, 116, 115, 116, 97, 109, 112, 0, 102, 108,
        111, 119, 95, 107, 101, 121, 115, 0, 115, 107, 0, 95, 95, 117, 56, 0, 117, 110, 115, 105,
        103, 110, 101, 100, 32, 99, 104, 97, 114, 0, 115, 107, 98, 0, 98, 112, 102, 95, 112, 114,
        111, 103, 114, 97, 109, 0, 99, 104, 97, 114, 0, 95, 108, 105, 99, 101, 110, 115, 101, 0,
        98, 112, 102, 95, 102, 108, 111, 119, 95, 107, 101, 121, 115, 0, 98, 112, 102, 95, 115,
        111, 99, 107, 0, 47, 114, 111, 111, 116, 47, 98, 112, 102, 95, 114, 115, 95, 104, 117, 98,
        47, 115, 111, 99, 107, 101, 116, 95, 102, 105, 108, 116, 101, 114, 47, 115, 114, 99, 47,
        98, 112, 102, 47, 112, 114, 111, 103, 114, 97, 109, 46, 98, 112, 102, 46, 99, 0, 105, 110,
        116, 32, 98, 112, 102, 95, 112, 114, 111, 103, 114, 97, 109, 40, 115, 116, 114, 117, 99,
        116, 32, 95, 95, 115, 107, 95, 98, 117, 102, 102, 32, 42, 115, 107, 98, 41, 0, 32, 32, 32,
        32, 105, 102, 32, 40, 115, 107, 98, 45, 62, 112, 107, 116, 95, 116, 121, 112, 101, 32, 33,
        61, 32, 80, 65, 67, 75, 69, 84, 95, 79, 85, 84, 71, 79, 73, 78, 71, 41, 0, 32, 32, 32, 32,
        108, 111, 110, 103, 32, 42, 118, 97, 108, 117, 101, 32, 61, 32, 98, 112, 102, 95, 109, 97,
        112, 95, 108, 111, 111, 107, 117, 112, 95, 101, 108, 101, 109, 40, 38, 116, 114, 97, 102,
        102, 105, 99, 44, 32, 38, 107, 101, 121, 41, 59, 0, 32, 32, 32, 32, 105, 102, 32, 40, 118,
        97, 108, 117, 101, 41, 0, 32, 32, 32, 32, 32, 32, 32, 32, 95, 95, 115, 121, 110, 99, 95,
        102, 101, 116, 99, 104, 95, 97, 110, 100, 95, 97, 100, 100, 40, 118, 97, 108, 117, 101, 44,
        32, 115, 107, 98, 45, 62, 108, 101, 110, 41, 59, 0, 32, 32, 32, 32, 114, 101, 116, 117,
        114, 110, 32, 48, 59, 0, 48, 58, 49, 0, 48, 58, 48, 0, 46, 109, 97, 112, 115, 0, 108, 105,
        99, 101, 110, 115, 101, 0, 115, 111, 99, 107, 101, 116, 0, 0, 0, 0, 0, 0, 159, 235, 1, 0,
        32, 0, 0, 0, 0, 0, 0, 0, 20, 0, 0, 0, 20, 0, 0, 0, 156, 0, 0, 0, 176, 0, 0, 0, 44, 0, 0, 0,
        8, 0, 0, 0, 20, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 28, 0, 0, 0, 16, 0, 0, 0, 20, 3, 0, 0, 9,
        0, 0, 0, 0, 0, 0, 0, 245, 1, 0, 0, 42, 2, 0, 0, 0, 104, 0, 0, 8, 0, 0, 0, 245, 1, 0, 0, 81,
        2, 0, 0, 14, 120, 0, 0, 24, 0, 0, 0, 245, 1, 0, 0, 81, 2, 0, 0, 23, 120, 0, 0, 40, 0, 0, 0,
        245, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 245, 1, 0, 0, 123, 2, 0, 0, 19, 140, 0,
        0, 88, 0, 0, 0, 245, 1, 0, 0, 178, 2, 0, 0, 9, 144, 0, 0, 96, 0, 0, 0, 245, 1, 0, 0, 193,
        2, 0, 0, 42, 152, 0, 0, 104, 0, 0, 0, 245, 1, 0, 0, 193, 2, 0, 0, 9, 152, 0, 0, 112, 0, 0,
        0, 245, 1, 0, 0, 240, 2, 0, 0, 5, 164, 0, 0, 16, 0, 0, 0, 20, 3, 0, 0, 2, 0, 0, 0, 8, 0, 0,
        0, 18, 0, 0, 0, 254, 2, 0, 0, 0, 0, 0, 0, 96, 0, 0, 0, 18, 0, 0, 0, 2, 3, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 120, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 184, 0, 0, 0, 0, 0, 0, 0, 192, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 1, 0, 0, 0, 6, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 120, 1, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 1, 0, 0,
        0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 248, 1, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 0,
        0, 0, 1, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 2, 0, 0, 0, 0, 0, 0,
        4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 95, 0, 0, 0, 9, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 2, 0,
        0, 0, 0, 0, 0, 16, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 16,
        0, 0, 0, 0, 0, 0, 0, 106, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 48, 2, 0, 0, 0, 0, 0, 0, 51, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 111, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 104, 9, 0, 0, 0, 0, 0, 0, 252, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    ];
}
