name: auto_release
on:
  push:
    branches: [ "release" ]
permissions:
  contents: write
jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
      - name: create version release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version=$(grep -E ^version Cargo.toml|awk -F "[\"]" '{print $2}')
          if [ -z "$version" ]; then echo "version not found"; exit 1; fi
          if ! gh release view "${version}" --json createdAt > /dev/null 2>&1; then
            git config --local user.email "admin@arloor.com"
            git config --local user.name "arloor"
            gh release create ${version} version -n "$version" --latest -t "$version"
          else 
            echo release already exists!
            exit 1
          fi
          
  